# @package agent
_target_: agent.icm.ICMAgent
name: icm
obs_dim: ??? # to be specified later
action_dim: ??? # to be specified later
enc_type: ???
device: ${device}
lr: 1e-4
batch_size: 1024
icm_scale: 1.0
sparsity: 1
reward_free: true
nstep: 1
critic_target_tau: 0.01
update_every_steps: 2
use_tb: ${use_tb}
use_wandb: ${use_wandb}
num_expl_steps: 5000
log_std_bounds: [-5, 2]
init_temperature: 0.1
critic_use_ln: false
critic_hidden_dims: [1024, 1024] #[512, 512, 256]
critic_spectral_norms: [false, false]
actor_use_ln: false
actor_hidden_dims: [1024, 1024] #[256, 256, 256]
actor_spectral_norms: [false, false]
repr_dim: 50
